"use client"
import React, { useState } from 'react';
import "./globals.css";
import "./all.min.css";
import 'swiper/css';
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
import { Swiper, SwiperSlide } from 'swiper/react';

config.autoAddCss = false
import Navbar from './Navbar/page'

import Footer from './Footer/page';
// import { Provider } from "@/components/ui/provider"

// import { usePathname } from 'next/navigation'


export default function RootLayout({children}:any) {
  // let x = usePathname()
  return (
    <>




    <html className="overflow-x-hidden">
    
      <body className='overflow-x-hidden w-full bg-[#121212] max-w-screen'>

      <div className="fixed top-0 z-100 right-0 left-0">
      {/* {isLogged? <UserNavbar/> : <Navbar />} */}
      <Navbar />

      </div>


          
   {children}

      </body>

      
    <footer className='relative footer md:px-30 px-10 pt-5 bottom- z-10 right-0 left-0'>
      
      <Footer/>

    </footer>
        
      
    </html>

    </>
  )
}













// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Footer from './Footer/page';

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
